### PR TITLE
Add macro `loopy-iter`

### PR DESCRIPTION
**Pull request by okamsn**
- This macro allows one to embed loop commands in arbitrary code.
- By default, loop commands require the use of keywords `for`, `accum`, or
  `exit`.  This requirement can be disabled with the flag `lax-naming`.
- Special macro arguments do not require a keyword, but not all aliases are
  allowed (for example `let*` as an alias of `with`).
- Loop commands are expanded in `lambda` forms, even when such forms are
  sharp-quoted.
- Document this feature in the Org doc and the README.

### CODE REVIEW

**Comment by okamsn** [comment]
Fixes #16.

@Luis-Henriquez-Perez, do you see things that you would like to be changed before this is merged?

I'm sure that adjustments to how different functions/forms are treated will be needed, and that these issues will be found as the macro is tested/used.  Ideally, the macro only needs to be aware of basic forms like `let` and `setq`.  For macros, it's calling `macroexpand-1` for each branch in the tree of code, which hopefully expands into those basic forms.

After merging, I will try to reduce duplication between `loopy` and `loopy-iter` once it seems that nothing more needs much changing.

**Comment by Luis-Henriquez-Perez** [comment]
I read over the documentation for iter. It seems good. You are probably right that the bulk of the changes we'll need to make to it will have to be fleshed out via usage. So I will switch to using this instead of loopy in my config.

One question I have is: are all clauses either non-conflicting with built-in Emacs functions or have an alias that is non-conflicting? Although the user can add their own, I think we should probably make sure there is each clause that does clash has at least one such alias by default.

**Comment by Luis-Henriquez-Perez** [comment]
Now that I think about it, is there currently a way to add a custom command for `loopy` iter?  Or would it be the same as for vanilla `loopy`? Is `loopy-iter` intended to eventually become the main macro or will loopy always offer both?

**Comment by Luis-Henriquez-Perez** [comment]
Also, perhaps we should advertise loopy to emacs reddit once again so that we can get more people using/testing it and hopefully creating issues.

**Comment by Luis-Henriquez-Perez** [comment]
Yet another note. I was just using `loopy-iter` in some code i posted below. I was using a `cond` and got an error about `error` not being a valid command. I realized that `loopy-iter` was trying to use loopy's cond command instead of `cond` itself. `loopy-iter` probably does not need command wrappers around existing special forms like `loopy` did because it can understand arbitrary commands. Therefore, I think we should remove the `when` `unless` `cond` commands from `loopy-iter`.

```elisp
(defun use-package-normalize/:xl-hook (name _ args)
  "Normalize ARGS."
  (loopy-iter (list elt args)
	      (cond ((symbolp elt)
		     (collect (cons elt (xl-emacs-modeify name))))
		    ((-cons-pair-p elt))
		    (t
		     (error "%s requires %s"))))
  ;; (->> args
  ;;      (-map-when #'symbolp (fn! (cons <> (xl-emacs-modeify name))))
  ;;      (-mapcat #'use-package%normalize-cons)
  ;;      (-map (fn! (cons (xl-emacs-hookify (car <>)) (cdr <>)))))
  )
```

**Comment by okamsn** [comment]
> I read over the documentation for iter. It seems good. You are probably right that the bulk of the changes we'll need to make to it will have to be fleshed out via usage. So I will switch to using this instead of loopy in my config.
> 
> One question I have is: are all clauses either non-conflicting with built-in Emacs functions or have an alias that is non-conflicting? Although the user can add their own, I think we should probably make sure that each clause that does clash has at least one such alias by default.
> 
> EDIT: Off the top of my head, I think `list` needs one. Also, perhaps `append`, `vconcat`, `sum` and `nconc`.

You are right. Not all loop commands currently have a good alternative name. 

For accumulation commands, other packages like using the "-ing" form of the word ("appending", "summing", etc.), but what do think would make good aliases for commands like `list`?  The use of the keyword `for` is already similar to what other packages use. 

> Now that I think about it, is there currently a way to add a custom command for `loopy` iter? Or would it be the same as for vanilla `loopy`? Is `loopy-iter` intended to eventually become the main macro or will loopy always offer both?

I would like to share as much functionality between the two as is reasonable, including custom commands and aliases. I think that it makes sense to offer both macros, because I think that the more basic `loopy` macro inherently has less edge cases to deal with. As it already works, I don't see any reason to get rid of it.

Regarding "main-ness", I see `loopy-iter` as another way to access the same features as `loopy`, which are the loop commands. Having both macros can hopefully allow one to express ideas more easily in cases where one would have to work around the limitations of the `do` loop command.

> Also, perhaps we should advertise loopy to emacs reddit once again so that we can get more people using/testing it and hopefully creating issues.

I plan to do this after merging this PR. When last I posted about it, people were mainly interested in how it compared to the Iterate package. Hopefully we get more detailed feedback this time.


> Yet another note. I was just using `loopy-iter` in some code i posted below. I was using a `cond` and got an error about `error` not being a valid command. I realized that `loopy-iter` was trying to use loopy's cond command instead of `cond` itself. `loopy-iter` probably does not need command wrappers around existing special forms like `loopy` did because it can understand arbitrary commands. Therefore, I think we should remove the `when` `unless` `cond` commands from `loopy-iter`.

Do you think that a user option of commands/aliases to ignore is sufficient for this?

**Comment by Luis-Henriquez-Perez** [comment]
> but what do think would make good aliases for commands like list? The use of the keyword for is already similar to what other packages use.

Not sure. `for` would be a good choice if possible.

> Do you think that a user option of commands/aliases to ignore is sufficient for this?

That would be OK. But I think then it would make sense for clauses like `cond` to be off by default for `loopy-iter` because they don't make sense for it. If it has the ability to read nested clauses, then that defeats the purpose the of clauses which were created to provide the illusion of artibrary nesting such as `cond` and `when` and `unless`.

**Comment by Luis-Henriquez-Perez** [comment]
In regards to posting it reddit, I would also recommend posting it on `r/lisp`. There you have a good chance of finding lisp hackers knowledgable about iter that can provide implmentation advice and critique.

**Comment by okamsn** [comment]
> > but what do think would make good aliases for commands like list? The use of the keyword for is already similar to what other packages use.
> 
> Not sure. `for` would be a good choice if possible.

I don't understand what you mean. Iterate and `cl-loop` use the keyword `for` for iterating through sequences (`(for VAR in LIST)` and `for VAR in LIST`, respectively), which is similar to the default behavior of `loopy-iter`, being `(for list VAR LIST)`.

Adding an alias like `for-in` is simple, but does not save many keystrokes when typing. 
 
> > Do you think that a user option of commands/aliases to ignore is sufficient for this?
> 
> That would be OK. But I think then it would make sense for clauses like `cond` to be off by default for `loopy-iter` because they don't make sense for it. If it has the ability to read nested clauses, then that defeats the purpose the of clauses which were created to provide the illusion of artibrary nesting such as `cond` and `when` and `unless`.

After experimenting, I think that it is better to always prefer built-in features to loop commands when `lax-naming` is active. 

For example, 

``` emacs-lisp
(collect my-collection (progn (expr i 2) i))
```

might expand into something like

``` emacs-lisp
(setq my-collection (append my-collection (list (progn (expr i 2) i)))
```

which needs to be further interpreted to expand the usage of `expr`, but would throw an error because the `list` and `append` would be treated as a loop commands instead of functions.

I've still added the user option for ignoring commands, since it might prove useful down the road.

**Comment by Luis-Henriquez-Perez** [comment]
> I don't understand what you mean. Iterate and cl-loop use the keyword for for iterating through sequences ((for VAR in LIST) and for VAR in LIST, respectively), which is similar to the default behavior of loopy-iter, being (for list VAR LIST).

Might be wierd but I thought that an alias for list could be `for`. So presumably if using `loopy-iter` and looping through a list with the `lax-naming` tag enabled you could do `(for VAR LIST)`, but if you don't have the flag you can do `(for list VAR LIST)`. Might be confusing though because `(for for VAR LIST)` is also possible. 

> Adding an alias like for-in is simple, but does not save many keystrokes when typing.

Some other potential aliases I thought of are `each` or `for-each`, though these are usually used to denote side-effects.

>  I think that it is better to always prefer built-in features to loop commands when lax-naming is active.

Yes, this is likely a good idea. The user should have to use the non-conflicting clauses for `loopy-iter` to guarantee the macro can distinguish.

**Comment by okamsn** [comment]
> > Also, perhaps we should advertise loopy to emacs reddit once again so that we can get more people using/testing it and hopefully creating issues.
> 
> I plan to do this after merging this PR. When last I posted about it, people were mainly interested in how it compared to the Iterate package. Hopefully we get more detailed feedback this time.

Also need to fix the Pcase destructuring, since we know that it's broken on Emacs 28.

**Comment by okamsn** [comment]
> Might be wierd but I thought that an alias for list could be `for`. So
> presumably if using `loopy-iter` and looping through a list with the
> `lax-naming` tag enabled you could do `(for VAR LIST)`, but if you don't have
> the flag you can do `(for list VAR LIST)`. Might be confusing though because
> `(for for VAR LIST)` is also possible.

I think that `for` alone might be too ambiguous.

>
> > Adding an alias like for-in is simple, but does not save many keystrokes when
> > typing.
>
> Some other potential aliases I thought of are `each` or `for-each`, though these
> are usually used to denote side-effects.

For now, I've added aliases based on the respective `for`-clauses from
`cl-loop`.  For example, `list` gets `in`, `array` gets `across`, and `seq` gets
`elements`.  I don't think that these aliases are particularly good, but they
should be familiar enough.

This is just another example of the challenge in naming things.

**Comment by Luis-Henriquez-Perez** [comment]
A question, can `loopy` be used to write loops for functions in `loopy-iter`? I noticed some of the functions in the source of `loopy-iter` could benefit from using `loopy`. Was wondering if there's a reason `loopy` can't be used to write `loopy-iter`.

**Comment by okamsn** [comment]
> Also need to fix the Pcase destructuring, since we know that it's broken on
> Emacs 28.

This is mostly done.  All that should be left is cleaning up that which is no
longer used and adding some more tests.

> A question, can `loopy` be used to write loops for functions in `loopy-iter`? I
> noticed some of the functions in the source of `loopy-iter` could benefit from
> using `loopy`. Was wondering if there's a reason `loopy` can't be used to write
> `loopy-iter`.

It probably could. I haven't checked how multi-file packages are byte-compiled.
I'm guessing that one benefit of using the built-in functions is that it might
be easier to debug problems, but I don't know that for sure.

**Comment by okamsn** [comment]
All of the tests are passing, and I think that this is ready to be merged.

User @luis-henriquez-perez, besides the pull requests you've made, is there
anything else that you would like to test or change before this is merged?  Have
you found more problems?

**Comment by Luis-Henriquez-Perez** [comment]
> User @Luis-Henriquez-Perez, besides the pull requests you've made, is there
anything else that you would like to test or change before this is merged? Have
you found more problems?

I haven't found any more problems in my usages of iter (I have been using it instead of `loopy` for my cases). I have no qualms with merging this.

**Comment by Luis-Henriquez-Perez** [comment]
Also, since iter can't use `list` and needs to use `in` which is not a great alias. Maybe we can add `each` as another alternative for `list`. I think it is slightly better.

**Comment by okamsn** [comment]
> Also, since iter can't use `list` and needs to use `in` which is not a great alias. Maybe we can add `each` as another alternative for `list`. I think it is slightly better.

This has been added.

**Pull request merged**
