### PR TITLE
Updating the docs

### PR DESCRIPTION
**Pull request by Luis-Henriquez-Perez**
This is a work in progress. I was reading over the docs and wanted to update a few things.

- First, where you mentioned how changing a variable conditionally is easier in `loopy`, I found it a bit unclear and was hoping you'd an example so people who might also be confused can better understand the difficulty/ease.

- Also, I mentioned initially and initially do.

- Then I noticed the accumulation variables needed some clarification.

- I found an extra newline in some heading too and I removed it.

I do have a few questions.
There's the info, the wiki, and the readme. What are the rules about what goes in what. I assume generally that the README is more casual and that the info manual should be more formal.

### CODE REVIEW

**Comment by okamsn** [comment]
Thanks for the help! I'm trying to merge the changes in #33 by the end of this
weekend, so you might wish to wait until after that.  Many of the examples and
more than a few of the paragraphs of explanation had to be changed.

1. I meant how, as far as I know, one can't do something like the below in
   `cl-loop`. Trying this out has shown that it currently doesn't work anymore,
   so I will fix this after merging the changes discussed in #33.

   I found limitations like this when trying to write commands for Selectrum
   using `cl-loop`, such as those in the file `example/loopy-examples.el` (which
   I must also update). My experience was, after initializing many variables in
   `with` clauses and having a large `do` clauses for most of the code in the
   loop, that using `cl-loop` in such cases is not sufficiently different from
   just writing normal Emacs Lisp.

   ``` emacs-lisp
   ;; NOTE: This doesn't currently work.
   ;; Should be '(6 7 8), but is currently
   ;; => (6 6 8 8 10)
   (loopy (list i '(1 2 3 4 5))
          (when (cl-oddp i)
            (list j '(6 7 8 9 10)))
          (collect j))
   ```

   I haven't been able to think of a short example to show why this conditional
   assignment is more useful than just using many `do` clauses.

2. Originally, there was much overlap between the readme, the Info document, and
   the wiki. I have been trying to make the situation so that

   - the README contains information about why `loopy` is useful and overview of
     it's features for those looking at the repo.

   - the Info document describes what `loopy` is for and how to use it.

   - The wiki contains information that might be of interest to those reading
     the README but that isn't needed in the README or the Info document.  For
     example, the timing comparisons between `loopy` and other libraries is
     probably too large for the README and does not belong in the Info document.

   I acknowledge that there is still overlap between the 3, and that there is
   still room for improvement.

**Comment by okamsn** [comment]
I have made the changes needed by #33 to the Org document, and have tried to improve the Texinfo export. Do you see anything lacking in its current state, beyond what you've already listed?

I don't believe that it would be fair of me to ask you to redo your work, so if you have other changes in mind, I can try to just do them on my copy, if that would be easier.

**Comment by okamsn** [comment]
> ``` elisp
> ;; NOTE: This doesn't currently work.
> ;; Should be '(6 7 8), but is currently
> ;; => (6 6 8 8 10)
> (loopy (list i '(1 2 3 4 5))
>        (when (cl-oddp i)
>         (list j '(6 7 8 9 10)))
>       (collect j))
> ```

So it turns out the the Iterate library just doesn't allow having clauses like `(for i in list)` lower than the top-level. I've realized that the quoted behavior is hard to achieve once you introduce a clause to skip to the next cycle of the loop.

```cl
;; Error: can't use `for' except at the top level.
(iter (for i from 1 to 10)
  (when (evenp i)
    (for j from 11 to 20)
    (collect j)))
```

**Comment by Luis-Henriquez-Perez** [comment]
> I don't believe that it would be fair of me to ask you to redo your work, so if you have other changes in mind, I can try to just do them on my copy, if that would be easier.

That's alright, I don't mind. I'll take a look at it right now.

**Comment by Luis-Henriquez-Perez** [comment]
Some things I wanted to mention after reading it. I will mention my impressions and general thoughts, which it is Ok to disagree with.

- after-do else-do

These keywords do the same thing. However, to me their names imply they do different things. When I think of `after-do` or `after` I think of something done after the loop no matter what. When I think of `else-do` or `else` I think of something done if some condition doesn't work out.

- finally-return

Got to say I hate typing this whole thing. I miss just typing `return` although I can see why there is a distinction between the two now. Maybe we could make an alias for this. Or maybe just let the user do it. It's no big deal either way.

- aliases

How is it that aliases are defined in loopy? Is it just creating a new entry in `lispy-common-command-parsers`. Maybe we should have a function provided for quick alias setting. Maybe we should include this in the docs as that might be something people might want to do.

- set

In emacs the set `set` function evaluates all of its arguments unlike `setq`. `expr` seems to work more like `setq` in this way than set. Again no biggie, just nothing my thoughts.

- pcase-destructuring

Does the pcase destructuring include logical. If so could we have that as an example? As in, what would happen if you tried to specify a list with to elements whose CAR is a string and CDR is an int.

```elisp
(pcase '("d" 3)
  (`(,(pred stringp) ,(pred integerp))
   t)
  (_
   nil))
```

- goal of working with cl-loop instead of replacing it

To be honest, to me the goal of having loopy suppliment `cl-loop` in situations where it is not sufficient is too modest for this project. This breath of this package, as well as the table it displays in the docs comparing `cl-loop` to itself screams of replacement to me, not augment. I can't think if a situation where I would have to use `cl-loop` given that I can use `loopy`. I can understand being hesitant to throw `cl-loop` out a window given its widespread usage in the Emacs community, but in all seriousness: `loopy` has better, more readable syntax, it can do anything `cl-loop` can do (and more, because it has `skip` and `leave`), it is designed with extensibility in mind, and its actively maintained on github. I don't see a "working together" or "augmenting" here.

**Comment by okamsn** [comment]
>     * after-do else-do
> 
> 
> These keywords do the same thing. However, to me their names imply they do different things. When I think of `after-do` or `after` I think of something done after the loop no matter what. When I think of `else-do` or `else` I think of something done if some condition doesn't work out.
> 
> EDIT: Thinking about it more, I can see

The `after-do`/`else-do` macro argument works the same as the `else` statement in Python. `before-do` and `after-do` both occur inside the `cl-block` with the `while` loop. For example,

```python
for i in [1, 2, 3, 4, 5]:
    print( "I:", i )
else:
    print("Loop completed.")
```

``` elisp
(loopy (list i (number-sequence 1 5))
 (do (message "I: %s" i))
 (else-do
  (message "Loop completed.")))
```

I understand that `after-do` and `finally-do` can seem like conflicting/redundant names.  I think that `else-do` / `else` should be kept as names, but what do you think could be changed to make this more understandable?

>     * finally-return
> 
> 
> Got to say I hate typing this whole thing. I miss just typing `return` although I can see why there is a distinction between the two now. Maybe we could make an alias for this. Or maybe just let the user do it. It's no big deal either way.

I agree that it is noticeably less convenient. The special macro arguments are hard-coded right now, so one can't currently add an alias for them. That's easy to change for arguments that don't affect how loop commands are expanded, like `finally-return`, `finally-do`,  `before-do`, and `else-do`. Aliases might not work well for `with` and `flag`.

> 
>     * aliases
> 
> 
> How is it that aliases are defined in loopy? Is it just creating a new entry in `lispy-common-command-parsers`. Maybe we should have a function provided for quick alias setting. Maybe we should include this in the docs as that might be something people might want to do.

Yes, the built-in aliases are just other symbols in `loopy--built-in-command-parsers`. Loopy finds the parsing functions based on the first symbol of the sexp, checking this variable and `loopy-custom-command-parsers`. Adding a user option for custom aliases is a good idea.

Maybe the function could be something like `(loopy-defalias NEW-NAME OLD-NAME)` which just adds a cons cell of `(NEW-NAME . OLD-NAME)` to a user option `loopy-custom-aliases`, which would be an alist. I think that that would work well.

Then, the order for finding the meaning of symbols would be 

1. custom aliases
2. custom commands
3. built-in commands

>     * set
> 
> 
> In emacs the set `set` function evaluates all of its arguments unlike `setq`. `expr` seems to work more like `setq` in this way than set.
> 
> EDIT: Then again, set is not often used (at least in my experience). Even more its more like `setq`. Nah, the name `setq` I think might be worse than hat it is.

I opted for `set` over `setq` because `set` only operates on one variable while `setq` can set  multiple variables in one call. I thought that would be less misleading.
 
>     * pcase-destructuring
> 
> 
> Does the pcase destructuring support logical patterns. If so could we have that as an example? As in, what would happen if you tried to specify a list with to elements whose CAR is a string and CDR is an int.
> 
> ```emacs-lisp
> (pcase '("d" 3)
>   (`(,(pred stringp) ,(pred integerp))
>    t)
>   (_
>    nil))
> ```
> 
> EDIT: Tried it out. Interesting, looks like it ignores it. This is the same as what `pcase-let` does. Not sure what should happen.
> 
> ```emacs-lisp
> ;; => ([3] [7])
> (loopy (flag pcase)
>        (list `(,(and (pred integerp) a) ,(and (pred stringp) b)) '((1 2) (3 4)))
>        (collect (vector (+ a b))))
> 
> ;; => 3
> ;; Using "wrong" logical pattern to see if I get an error or something like that. But it is just ignored. Interesting.
> 
> (pcase-let* ((`(,(and (pred stringp) a) ,(and (pred stringp) b)) (list 1 2)))
>   (+ a b))
> ```

The function `loopy-pcase--get-variable-values` in `loopy-pcase.el` just expands a call to `pcase-let` and returns the bindings it creates. I think this is the best approach, and that it is enough to say that it uses `pcase-let`. Whether `pcase-let` works well enough is up to the users and authors of Pcase.

>     * goal of working with cl-loop instead of replacing it
> 
> 
> To be honest, to me the goal of having loopy supplement `cl-loop` in situations where it is not sufficient is too modest for this project. This breath of this package, as well as the table it displays in the docs comparing `cl-loop` to itself screams of replacement to me, not augment. I can't think of a situation where I would have to use `cl-loop` given that I can use `loopy`. I can understand being hesitant to throw `cl-loop` out a window given its widespread usage in the Emacs community, but in all seriousness: `loopy` has better, more readable syntax, it can do anything `cl-loop` can do (and more, because it has `skip` and `leave`), it is designed with extensibility in mind, and its actively maintained on github. I don't see a "working together" or "augmenting" here.
> 
> EDIT: So the gist is maybe we should make a bolder statement of replacing cl-loop. I don't think it makes a lot of sense to use both given the huge overlap in functionality.

There are still some features that I haven't decided how to satisfactorily add to `loopy`, such as good wrappers for `maphash` or `map-keymap`. The naive way is to just use those functions to create a list of values (which is indeed what some libraries do), but I've been waiting to learn of a better way.

`loopy` might be close to doing all that `cl-loop` does (personally, it handles all of my use cases), but it isn't as optimized as `cl-loop`, and, [as seen on the wiki](https://github.com/okamsn/loopy/wiki/speed-comparisons), both are still overkill for some common situations. Because the available solutions are best used in different cases, I believe that some talk of "supplementing" is honest/helpful, even if not needed for `cl-loop` specifically.

**Comment by Luis-Henriquez-Perez** [comment]
> I think that else-do / else should be kept as names, but what do you think could be changed to make this more understandable?

On second thought I think they should be kept as well. It's good that we're having this discussion in any case, at the very least so others reading this can understand the reasoning. We try to make names as good as possible, but sometimes there's only so much the english language can do.

> The special macro arguments are hard-coded right now, so one can't currently add an alias for them. That's easy to change for arguments that don't affect how loop commands are expanded, like finally-return, finally-do, before-do, and else-do.

Ideally, all (if not, as many as possible) loopy clauses should be implemented the same way as custom user clauses would be added. The only difference being they come with loopy by default. This would make `loopy` more modular, customizable, internally consistent, and as a bonus provide users with more examples of how to add clauses.

> I think this is the best approach, and that it is enough to say that it uses pcase-let. Whether pcase-let works well enough is up to the users and authors of Pcase.

Agreed. I was just curious about that behavior.

>  I believe that some talk of "supplementing" is honest/helpful, even if not needed for cl-loop specifically.

Certainly, talk of supplementing is appropriate when discussing loopy as a tool used with `dash`, or `seq`, or `map` I completely agree there. They take a very different approach, which is in some cases more appropriate than using `loopy`. I was nitpicking because it is hard for me to imagine using both `cl-loop` and `loopy` together, supplementing one another in code. To me, the relationship between `cl-loop` and `loopy` is more alternative than supplementary.

**Comment by okamsn** [comment]
I've added alias for loop commands and all of the special macro arguments.

For now, I'm going to hold off on converting the special macro arguments into
loop commands. They share requirements that make them conceptually similar, and
I would prefer converting all of them, not just most of them.

**Pull request merged**
